import React, { useState } from 'react';
import { AlertCircle, X } from 'lucide-react';

interface AiDisclosureBannerProps {
  className?: string;
  dismissible?: boolean;
}

export default function AiDisclosureBanner({ 
  className = '', 
  dismissible = true 
}: AiDisclosureBannerProps) {
  const [isDismissed, setIsDismissed] = useState(() => {
    return localStorage.getItem('ai-disclosure-dismissed') === 'true';
  });

  const handleDismiss = () => {
    localStorage.setItem('ai-disclosure-dismissed', 'true');
    setIsDismissed(true);
  };

  if (isDismissed) return null;

  return (
    <div className={`bg-blue-50 dark:bg-blue-900/20 border-t border-blue-200 dark:border-blue-800 py-2 ${className}`}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-2 text-sm text-blue-700 dark:text-blue-300">
            <AlertCircle className="w-4 h-4 flex-shrink-0" />
            <span>Content generated by artificial intelligence - not independently verified for accuracy or completeness</span>
          </div>
          
          {dismissible && (
            <button
              onClick={handleDismiss}
              className="p-1 rounded-full hover:bg-blue-100 dark:hover:bg-blue-800/50 transition-colors"
              aria-label="Dismiss AI disclosure"
            >
              <X className="w-4 h-4 text-blue-600 dark:text-blue-400" />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}