import React, { useState } from 'react';
import { X, FileText, ExternalLink, AlertCircle } from 'lucide-react';
import Modal from './ui/Modal';
import Button from './ui/Button';

export default function LegalDisclaimer() {
  const [showModal, setShowModal] = useState(false);

  return (
    <>
      {/* AI Disclosure Banner */}
      <div className="bg-blue-50 dark:bg-blue-900/20 border-t border-blue-200 dark:border-blue-800 py-2 text-center text-sm text-blue-700 dark:text-blue-300">
        <div className="flex items-center justify-center gap-2">
          <AlertCircle className="w-4 h-4" />
          <span>Content generated by artificial intelligence - not independently verified for accuracy or completeness</span>
        </div>
      </div>

      {/* Footer with Legal Links */}
      <footer className="bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 py-6">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="text-sm text-slate-500 dark:text-slate-400">
              <span>© {new Date().getFullYear()} ShowerGPT</span>
              <span className="mx-2">•</span>
              <span>Demo Application</span>
              <span className="mx-2">•</span>
              <span>AI-Generated Content</span>
              <span className="mx-2">•</span>
              <span>No Warranties</span>
              <span className="mx-2">•</span>
              <span>Privacy Protected</span>
            </div>
            
            <div>
              <Button
                onClick={() => setShowModal(true)}
                variant="ghost"
                size="sm"
                leftIcon={<FileText className="w-4 h-4" />}
              >
                Terms & Privacy
              </Button>
            </div>
          </div>
        </div>
      </footer>

      {/* Terms & Privacy Modal */}
      <Modal
        isOpen={showModal}
        onClose={() => setShowModal(false)}
        title="Terms of Use & Privacy Policy"
        size="lg"
      >
        <div className="p-6 space-y-6 max-h-[70vh] overflow-y-auto">
          <section className="space-y-3">
            <h3 className="text-xl font-bold text-slate-800 dark:text-slate-200">
              Legal Status & Purpose
            </h3>
            <p className="text-slate-600 dark:text-slate-400">
              This application is a demonstration prototype created solely for hackathon/educational purposes.
              It is not intended for commercial use or production environments.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-xl font-bold text-slate-800 dark:text-slate-200">
              AI-Generated Content Disclaimer
            </h3>
            <p className="text-slate-600 dark:text-slate-400">
              Content is generated using OpenAI's technology and is subject to their terms of service and usage policies.
              All AI-generated content is provided strictly "as-is" and "with all faults".
              No warranties or guarantees regarding accuracy, reliability, appropriateness, originality or fitness for any purpose are made.
              Users acknowledge inherent limitations and potential errors in AI-generated content.
            </p>
            <p className="text-slate-600 dark:text-slate-400">
              For more information about OpenAI's terms, please visit{' '}
              <a 
                href="https://openai.com/policies/terms-of-use" 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-blue-600 dark:text-blue-400 hover:underline inline-flex items-center gap-1"
              >
                OpenAI's Terms of Use
                <ExternalLink className="w-3 h-3" />
              </a>
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-xl font-bold text-slate-800 dark:text-slate-200">
              Intellectual Property Rights
            </h3>
            <p className="text-slate-600 dark:text-slate-400">
              Users retain full ownership rights to their original input prompts and data.
              AI-generated outputs may not qualify for copyright protection under current law.
              No claim of ownership is made on AI-generated content.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-xl font-bold text-slate-800 dark:text-slate-200">
              Data Collection & Privacy
            </h3>
            <p className="text-slate-600 dark:text-slate-400">
              Minimal data collection is limited to essential application functionality.
              No personal data is sold or shared with third parties.
              Anonymous usage metrics may be collected for application improvement.
              Data retention is limited to necessary operational periods.
            </p>
            <p className="text-slate-600 dark:text-slate-400">
              When using OpenAI's services, your prompts may be processed according to their privacy policy. Please review{' '}
              <a 
                href="https://openai.com/policies/privacy-policy" 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-blue-600 dark:text-blue-400 hover:underline inline-flex items-center gap-1"
              >
                OpenAI's Privacy Policy
                <ExternalLink className="w-3 h-3" />
              </a>
              {' '}for more information.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-xl font-bold text-slate-800 dark:text-slate-200">
              User Acknowledgment
            </h3>
            <p className="text-slate-600 dark:text-slate-400">
              Usage of this application constitutes acceptance of these terms.
              Users must be 13+ years of age.
              For questions or concerns, please contact <a href="mailto:contact@showergpt.app" className="text-blue-600 dark:text-blue-400 hover:underline">contact@showergpt.app</a>.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-xl font-bold text-slate-800 dark:text-slate-200">
              Limitation of Liability
            </h3>
            <p className="text-slate-600 dark:text-slate-400">
              To the maximum extent permitted by law, the creators and operators of this application shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
            </p>
            <ul className="list-disc pl-5 text-slate-600 dark:text-slate-400 space-y-1">
              <li>Your use or inability to use the application</li>
              <li>Any content obtained from the application</li>
              <li>Unauthorized access to or use of our servers or any personal information</li>
              <li>Any interruption or cessation of transmission to or from the application</li>
              <li>Any bugs, viruses, or other harmful code that may be transmitted through the application</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h3 className="text-xl font-bold text-slate-800 dark:text-slate-200">
              Changes to Terms
            </h3>
            <p className="text-slate-600 dark:text-slate-400">
              We reserve the right to modify these terms at any time. We will provide notice of significant changes by updating the date at the top of these terms and by maintaining a current version of the terms at this location.
            </p>
          </section>

          <div className="pt-4 border-t border-slate-200 dark:border-slate-700">
            <p className="text-sm text-slate-500 dark:text-slate-400 italic">
              Last updated: June 30, 2025
            </p>
          </div>
        </div>
      </Modal>
    </>
  );
}